using MathGame.AbstractBases;
using MathGame.CoreUtilities;
using MathGame.GameQuestion;

namespace MathGame.GameWindows;

public class HistoryWindow : WindowBase
{
    private int _currentPage = 1;
    private readonly int _rowsPerPage = 15;

    // get the total page
    private int TotalPages
    {
        get
        {
            int actualTotalRecords = GameEngine.GameHistoryTable.Count;
            return Math.Max(1, (actualTotalRecords + _rowsPerPage - 1) / _rowsPerPage);
        }
    }


    public override void Render()
    {
        // setting up the input handler
        InputHandler.CurrentErrorLocation = 2;
        InputHandler.SetActiveOptions = "np";

        // calculating the total number of element to skip
        int skipAmount = (_currentPage - 1) * _rowsPerPage;

        // getting via link the total pages to use
        var rowsToDisplay = GameEngine.GameHistoryTable
            .OrderByDescending(r => r.Id) // Get the latest games first
            .Skip(skipAmount) 
            .Take(_rowsPerPage)
            .ToList();
        // setting the space to offset before printing the table

        int offset = 11;
        // this is generated by AI not me to save some time
        string rowFormat = "| {0,-4} | {1,-10} | {2,-7} | {3,-10} | {4,-8} | {5,-10} | {6,-10} |";
        
        // set the cursor to the offset to begin flushing the table date
        Console.SetCursorPosition(0, offset);
        Console.Write(string.Format(
            rowFormat, "Id", "start Time", " Score", "Difficulty", "Op", "Q Type",
            "Total Qs"
        ));
        Console.Write("\r\n");
        Console.Write("|------|------------|---------|------------|----------|------------|------------|");
        Console.Write("\r\n");
        offset++;

        // iterate through the rows to display to flush the data
        foreach (var record in rowsToDisplay)
        {
            
            offset++;
            Console.SetCursorPosition(0, offset);
            Console.Write(rowFormat,
                record.Id,
                record.PlayedDate.ToString("HH:mm:ss"),
                record.TotalScore,
                record.Difficulty,
                record.Operation switch
                {
                    GameOperation.Random => "Random",
                    GameOperation.Subtraction => "-",
                    GameOperation.Multiplication => "x",
                    GameOperation.Division => "÷",
                    GameOperation.Addition => "+",
                    _ => ""
                },
                record.QuestionType,
                record.TotalNumberOfQuestions);
            Console.Write("\r\n");
        }

        // reset the cursor back
        Console.SetCursorPosition(0, 0);
        Console.WriteLine($"Page {_currentPage} of {TotalPages}");
        
        // prepare the tips
        string[] tip =
        [
            "type [n] to move to the next page",
            "type [p] to move back to the previous page",
            "type [q] to return back to the main menu"
        ];

        // ask for inputs
        InputHandler.InputPrompt(tip);
    }

    // process inputs
    public override WindowMap ProcessInput(string userInput)
    {
        switch (userInput)
        {
            // move next page
            case "n":
                // check the possibility of the transition
                if (_currentPage < TotalPages)
                {
                    _currentPage++;
                }

                WindowManager.CurrentWindow = WindowMap.HistoryWindow;
                break;

            // move back to the previous page
            case "p":
                // check the possibility of the transition
                if (_currentPage > 1)
                {
                    _currentPage--;
                }

                WindowManager.CurrentWindow = WindowMap.HistoryWindow;
                break;

            case "q":
                // go back to main maun
                WindowManager.CurrentWindow = WindowMap.MainMenu;
                break;
            default:
                break;
        }

        return WindowManager.CurrentWindow;
    }
}